
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=


spring.jpa.show-sql=
bot.token=
bot.name=


logging.level.com.example.loggerDraft.service=
spring.liquibase.change-log=
path.to.avatars.folder=